Week14Day5/Models/ErrorViewModel.cs
using System;

namespace Week14Day5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Week14Day5/Models/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Week14Day5.Models
{
    public class MenuViewModel
    {
        [DisplayName("MenuID")]
        public int Id { get; set; }

        [Required]
        [DisplayName("Nome Menu")]
        public string Nome { get; set; }

        public List<PiattoViewModel> Piatti { get; set; } = new List<PiattoViewModel>();
    }
}

Week14Day5/Models/PiattoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Week14Day5.Models
{
    public class PiattoViewModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [DisplayName("Nome Piatto")]
        public string Nome { get; set; }
        public string Descrizione { get; set; }
        public _Tipologia Tipologia { get; set; }
        public decimal Prezzo { get; set; }


        //FK
        public int MenuId { get; set; }
        public MenuViewModel Menu { get; set; }
    }

    public enum _Tipologia
    {
        Primo,
        Secondo,
        Contorno,
        Dolce
    }
}

Week14Day5/Models/UtenteLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Week14Day5.Models
{
    public class UtenteLoginViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required, DataType(DataType.Password)]
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Week14Day5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Week14Day5.Models;

namespace Week14Day5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Week14Day5/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Week14Day5.Core.BusinessLayer;
using Week14Day5.Helper;
using Week14Day5.Models;

namespace Week14Day5.Controllers
{
    public class MenuController : Controller
    {
        private readonly IBusinessLayer BL;

        public MenuController(IBusinessLayer bl)
        {
            BL = bl;
        }

        #region CRUD
        [HttpGet]
        public IActionResult Index()
        {
            var menu = BL.GetAllMenus();

            List<MenuViewModel> menuViewModel = new List<MenuViewModel>();

            foreach (var item in menu)
            {
                menuViewModel.Add(item.ToMenuViewModel());
            }

            return View(menuViewModel);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var menu = BL.GetAllMenus().FirstOrDefault(m => m.Id == id);

            var menuViewModel = menu.ToMenuViewModel();

            return View(menuViewModel);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Create(MenuViewModel menuViewModel)
        {
            if (ModelState.IsValid)
            {
                var menu = menuViewModel.ToMenu();
                BL.AddMenu(menu);
                return RedirectToAction(nameof(Index));
            }
            return View(menuViewModel);
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            var menu = BL.GetAllMenus().FirstOrDefault(m => m.Id == id);
            var menuViewModel = menu.ToMenuViewModel();
            return View(menuViewModel);
        }


        [HttpPost]
        public IActionResult Update(MenuViewModel menuViewModel)
        {
            if (ModelState.IsValid)
            {
                var menu = menuViewModel.ToMenu();
                BL.EditMenu(menu);
                return RedirectToAction(nameof(Index));
            }
            return View(menuViewModel);
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var menu = BL.GetAllMenus().FirstOrDefault(m => m.Id == id);
            var menuViewModel = menu.ToMenuViewModel();
            return View(menuViewModel);
        }


        [HttpPost]
        public IActionResult Delete(MenuViewModel menuViewModel)
        {
            if (ModelState.IsValid)
            {
                var menu = menuViewModel.ToMenu();
                BL.DeleteMenu(menu.Id);
                return RedirectToAction(nameof(Index));

            }
            return View(menuViewModel);
        }

        #endregion
    }

}

Week14Day5/Controllers/PiattiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Week14Day5.Core.BusinessLayer;
using Week14Day5.Helper;
using Week14Day5.Models;

namespace Week14Day5.Controllers
{
    public class PiattiController : Controller
    {
        private readonly IBusinessLayer BL;

        public PiattiController(IBusinessLayer bl)
        {
            BL = bl;
        }

        #region CRUD
        [HttpGet]
        public IActionResult Index()
        {
            var piatti = BL.GetAllPiatti();

            List<PiattoViewModel> piattiViewModel = new List<PiattoViewModel>();

            foreach (var item in piatti)
            {
                piattiViewModel.Add(item.ToPiattoViewModel());
            }

            return View(piattiViewModel);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);

            var piattoViewModel = piatto.ToPiattoViewModel();

            return View(piattoViewModel);

        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Create(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                var piatto = piattoViewModel.ToPiatto();
                BL.AddPiatto(piatto);
                return RedirectToAction(nameof(Index));
            }
            return View(piattoViewModel);
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);
        }


        [HttpPost]
        public IActionResult Update(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                var piatto = piattoViewModel.ToPiatto();
                BL.EditPiatto(piatto);
                return RedirectToAction(nameof(Index));
            }
            return View(piattoViewModel);
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);
        }


        [HttpPost]
        public IActionResult Delete(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                var piatto = piattoViewModel.ToPiatto();
                BL.DeletePiatto(piatto.Id);
                return RedirectToAction(nameof(Index));
            }
            return View(piattoViewModel); ;
        }

        #endregion
    }
}

Week14Day5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Week14Day5/Views/Menu/Create.cshtml
@model MenuViewModel
<h1>Inserisci nuovo menu: </h1>

<form method="post">
    <div class="form-group">
        <input type="hidden" asp-for="Id" class="form-control" value="0" />
    </div>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    
    <input type="submit" value="Salva" class="btn btn-secondary" />
    <input type="reset" value="Reset" class="btn btn-secondary" />
    <a class="btn btn-secondary" asp-controller="Prodotti" asp-action="Index" role="button">Indietro</a>
</form>

Week14Day5/Views/Menu/Delete.cshtml
@model MenuViewModel
<form method="post">
    <p>Sei sicuro di voler eliminare questo prodotto: @Model.Id - @Model.Nome?</p>

    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" readonly />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" readonly />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <input type="submit" value="Conferma" class="tbn btn-danger" />
    <a class="btn btn-primary" asp-controller="Menu" asp-action="Index" role="button">Annulla</a>
</form>

Week14Day5/Views/Menu/Details.cshtml
@model MenuViewModel
<h1>MENU</h1>

<table class="table table-hover table-bordered table table-striped">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>Nome</th>
            <td>@Model.Nome</td>
        </tr>
        <tr>
            <th>Piatti</th>
            @foreach (var item in Model.Piatti)
            {

                        <th>@item.Nome</th>
                        <td>Prezzo: @item.Prezzo Euro</td>
            }
        </tr>


    </tbody>
</table>

Week14Day5/Views/Menu/Index.cshtml
@model List<MenuViewModel>
<h1>Lista Menu</h1>


    <a asp-controller="Menu" asp-action="Create" class="btn btn-primary">Aggiungi Menu</a>

<table class="table table-hover table-bordered table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome Menu</th>
            <th>Azioni</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Nome</td>
                <td>
                    <a asp-controller="Menu" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Visualizza</a>
                    <a asp-controller="Menu" asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary">Modifica</a>
                    <a asp-controller="Menu" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                    
                </td>

            </tr>
        }
    </tbody>

</table>

Week14Day5/Views/Menu/Update.cshtml
@model MenuViewModel
<h1>Modifica menu: </h1>

<form method="post">
    <div class="form-group">
        <input type="hidden" asp-for="Id" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <input type="submit" value="Salva" class="btn btn-secondary" />
    <input type="reset" value="Reset" class="btn btn-secondary" />
    <a class="btn btn-secondary" asp-controller="Menu" asp-action="Index" role="button">Indietro</a>
</form>

Week14Day5/Views/Piatti/Create.cshtml
@model PiattoViewModel
<h1>Inserisci nuovo piatto: </h1>

<form method="post">
    <div class="form-group">
        <input type="hidden" asp-for="Id" class="form-control" value="0" />
    </div>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Descrizione"></label>
        <input asp-for="Descrizione" class="form-control" />
        <span asp-validation-for="Descrizione" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Tipologia"></label>
        <select asp-for="Tipologia" asp-items="Html.GetEnumSelectList<_Tipologia>()">
            <option selected>Seleziona una tipologia</option>
        </select>
        <span asp-validation-for="Tipologia" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Prezzo"></label>
        <input asp-for="Prezzo" class="form-control" />
        <span asp-validation-for="Prezzo" class="text-danger"></span>
    </div>
    <input type="submit" value="Salva" class="btn btn-secondary" />
    <input type="reset" value="Reset" class="btn btn-secondary" />
    <a class="btn btn-secondary" asp-controller="Piatti" asp-action="Index" role="button">Indietro</a>
</form>

Week14Day5/Views/Piatti/Delete.cshtml
@model PiattoViewModel
<form method="post">
    <p>Sei sicuro di voler eliminare questo prodotto: @Model.Id - @Model.Nome?</p>

    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" readonly />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" readonly />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Descrizione"></label>
        <input asp-for="Descrizione" class="form-control" readonly />
        <span asp-validation-for="Descrizione" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Tipologia"></label>
        <input asp-for="Tipologia" class="form-control" readonly />
    </div>

    <div class="form-group">
        <label asp-for="Prezzo"></label>
        <input asp-for="Prezzo" class="form-control" readonly />
        <span asp-validation-for="Prezzo" class="text-danger"></span>
    </div>


    <input type="submit" value="Conferma" class="tbn btn-danger" />
    <a class="btn btn-primary" asp-controller="Prodotti" asp-action="Index" role="button">Annulla</a>
</form>

Week14Day5/Views/Piatti/Details.cshtml
@model PiattoViewModel
<h1>Dettagli del piatto:</h1>

<table class="table table-hover table-bordered table table-striped">
    <tbody>
        <tr>
            <th>ID</th>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <th>Nome</th>
            <td>@Model.Nome</td>
        </tr>
        <tr>
            <th>Prodotto</th>
            <td>@Model.Descrizione</td>
        </tr>
        <tr>
            <th>Tipologia</th>
            <td>@Model.Tipologia</td>
        </tr>
        <tr>
            <td>Prezzo</td>
            <td>@Model.Prezzo</td>
        </tr>
        <tr>
            <th>Associato al Menu:</th>
            <td>@Model.MenuId</td>
        </tr>
    </tbody>
</table>

Week14Day5/Views/Piatti/Index.cshtml
@model List<PiattoViewModel>
<h1>Lista dei piatti</h1>


<a asp-controller="Piatti" asp-action="Create" class="btn btn-primary">Aggiungi Piatto</a>

<table class="table table-hover table-bordered table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome piatto</th>
            <th>Azioni</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Nome</td>
                <td>
                    <a asp-controller="Piatti" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Visualizza</a>
                    <a asp-controller="Piatti" asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary">Modifica</a>
                    <a asp-controller="Piatti" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>

            </tr>
        }
    </tbody>

</table>

Week14Day5/Views/Piatti/Update.cshtml
@model PiattoViewModel
<h1>Modifica piatto: </h1>

<form method="post">
    <div class="form-group">
        <input type="hidden" asp-for="Id" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Descrizione"></label>
        <input asp-for="Descrizione" class="form-control" />
        <span asp-validation-for="Descrizione" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Tipologia"></label>
        <select asp-for="Tipologia" asp-items="Html.GetEnumSelectList<_Tipologia>()">
            <option selected>Seleziona una tipologia</option>
        </select>
        <span asp-validation-for="Tipologia" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Prezzo"></label>
        <input asp-for="Prezzo" class="form-control" />
        <span asp-validation-for="Prezzo" class="text-danger"></span>
    </div>
    <input type="submit" value="Salva" class="btn btn-secondary" />
    <input type="reset" value="Reset" class="btn btn-secondary" />
    <a class="btn btn-secondary" asp-controller="Piatti" asp-action="Index" role="button">Indietro</a>
</form>

Week14Day5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ristorante</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Week14Day5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Piatti" asp-action="Index">Piatti</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark text-center text-white">
        <div class="container">
            Week14Day5: Ristorante© - Angelica Cortez
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>